"""Compact JEPA research primitives for time-series experiments."""

from jepa.config import (
    BinanceDataConfig,
    ExperimentConfig,
    MaskedPatchesConfig,
    ObjectiveConfig,
    ObjectiveKind,
    PairedReplicateSeeds,
    apply_paired_replicate,
    config_from_dict,
    config_identity_hash,
    derive_paired_replicate,
    load_config,
)
from jepa.data import (
    DatasetBundle,
    LatentDynamicsDataset,
    WindowDataset,
    build_dataset_bundle,
    build_dataset_splits,
    generate_system,
)
from jepa.metrics import (
    MetricValue,
    RepresentationMetrics,
    RidgeProbe,
    WeightedMean,
    compute_representation_metrics,
    fit_ridge_probe,
    global_gradient_norm,
    ridge_r2_score,
)
from jepa.models import (
    LinearEncoder,
    LinearPredictor,
    MaskedPatchPredictor,
    TanhEncoder,
    TanhPredictor,
    build_masked_model_pair,
    build_model_pair,
)
from jepa.reporting import SweepResult, aggregate_rows, run_sweep, variant_label
from jepa.training import (
    JEPACore,
    OptimizationPolicy,
    TrainResult,
    build_jepa_core,
    build_masked_jepa_core,
    build_run_id,
    compute_loss,
    compute_masked_loss,
    masked_patch_indices,
    optimizer_parameters,
    resolve_policy,
    train_experiment,
    train_step,
)

__all__ = [
    "ExperimentConfig",
    "BinanceDataConfig",
    "DatasetBundle",
    "JEPACore",
    "LatentDynamicsDataset",
    "MaskedPatchPredictor",
    "MaskedPatchesConfig",
    "LinearEncoder",
    "LinearPredictor",
    "MetricValue",
    "OptimizationPolicy",
    "ObjectiveConfig",
    "ObjectiveKind",
    "PairedReplicateSeeds",
    "RepresentationMetrics",
    "RidgeProbe",
    "TanhEncoder",
    "TanhPredictor",
    "TrainResult",
    "SweepResult",
    "WeightedMean",
    "WindowDataset",
    "apply_paired_replicate",
    "aggregate_rows",
    "build_dataset_bundle",
    "build_dataset_splits",
    "build_jepa_core",
    "build_masked_jepa_core",
    "build_masked_model_pair",
    "build_model_pair",
    "build_run_id",
    "compute_loss",
    "compute_masked_loss",
    "compute_representation_metrics",
    "config_from_dict",
    "config_identity_hash",
    "derive_paired_replicate",
    "generate_system",
    "global_gradient_norm",
    "load_config",
    "masked_patch_indices",
    "fit_ridge_probe",
    "optimizer_parameters",
    "resolve_policy",
    "ridge_r2_score",
    "run_sweep",
    "train_experiment",
    "train_step",
    "variant_label",
]

__version__ = "0.1.0"
